#!/bin/bash
#
# Copyright (c) 2015-2018  Terry Xi
# All Rights Reserved.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

function help_text() {
    echo "usage: push_plugin [-h] REMOTE_NAME PLUGIN_NAME [PLUGIN_VER] ..."
    exit
}

[ "$1" == "-h" ] || [ "$1" == "--help" ] || [ "$1" == "-help" ] && {
    help_text
}

PWD=$(pwd)


function push_plugin() {
    local target_branch=$1
    local target_remote=$3
    git push $target_remote $target_branch
}

function main() {
    local target_branch=$1
    local target_ver=$2
    local target_remote=$3
    local branch=$(git branch -a| grep remotes | grep "$target_remote" | grep "$target_ver" | grep "$target_branch" | awk -F'/' '{print $3}')
    [ -z "$branch" ] && {
        return
    }
    push_plugin "$branch" "$target_remote"
}

remote=$1
name=$2
ver=$3
[ -z "$ver" ] && {
    ver="0.1.0"
}
if [ "$remote" != "" ] && [ "$name" != "" ] && {
    main "$branch" "$ver" "$remote"
} || {
    help_text
}

